---
title: "soccR"
author: "Anatole GAYANT, Jules AVIGNON, Clément PEREON"
date: "2023-04-28"
output: 
  html_document
---

# API

On s'intéresse à l'édition 2020-2021 de la Ligue des champions.
Les données proviennent du site : https://www.football-data.org/

```{r, warning=FALSE, message=FALSE}
library(httr)
library(jsonlite)

# Récupération des données de tous les matchs de la Champions League
url <- "https://api.football-data.org/v4/competitions/CL/matches?season=2020"
response <- GET(url, add_headers("X-Auth-Token" = "d0d8b5553bd34025bac768b663973df2"))
data <- fromJSON(rawToChar(response$content))
matches <- data$matches
```

## Liste des matches

```{r, message=FALSE}
library(dplyr)
library(DT)
library(ggplot2)

matches_tbl <- as_tibble(matches)

matches_scores <-
  select(matches_tbl, homeTeam, awayTeam, score, utcDate) |>
  mutate(
    homeTeam_name = pull(homeTeam, "name"),
    awayTeam_name = pull(awayTeam, "name"),
    home_score = pull(score$fullTime, "home"),
    away_score = pull(score$fullTime, "away"),
    total_score = paste(home_score, "-", away_score),
    date = as.Date(utcDate))|>
  select(homeTeam_name,
         awayTeam_name,
         total_score,
         date) |>
  arrange(desc(matches_tbl$utcDate))

datatable(matches_scores, options = list(pageLength = 10, lengthMenu = c(10, 20, 50)), 
          filter = "top", rownames = FALSE,
          colnames = c("Home Team", "Away Team", "Total Score", "Date"),
          caption = "Tableau des scores Champions League 2021")

```

## Association du tour

```{r, message=FALSE, Avis = FALSE}
matches_scores$tour[1] <- "finale"
matches_scores$tour[2:5] <- "demis"
matches_scores$tour[6:13] <- "quarts"
matches_scores$tour[14:29] <- "huitiemes"
matches_scores$tour[30:nrow(matches_scores)] <- NA
matches_scores <-  na.omit(matches_scores)
```

## Représentation graphique des scores

```{r, fig.align='center'}
# Transformation du format des scores

matches_scores$home_score <- as.numeric(sub("^([0-9]+) - ([0-9]+)$", "\\1", matches_scores$total_score))
matches_scores$away_score <- as.numeric(sub("^([0-9]+) - ([0-9]+)$", "\\2", matches_scores$total_score))

# Création de la variable 'winner'
matches_scores$winner <- with(matches_scores, ifelse(home_score > away_score, homeTeam_name, ifelse(home_score < away_score, awayTeam_name, "Draw")))

# Création du graphique avec ggplot2
ggplot(matches_scores, aes(x = homeTeam_name, y = awayTeam_name, fill = tour)) + 
  geom_tile(aes(width = 0.9, height = 0.9), color = "white", size = 0.5) +
  geom_text(aes(label = total_score), size = 5) +
  scale_fill_discrete(name = "Tour") +
  theme_minimal() +
  labs(x = NULL, y = NULL) +
  coord_fixed() +
  theme(axis.text.x = element_text(angle = 45, hjust=1))

```

```{r, warning=FALSE, message=FALSE}
library(ggpubr)
library(ggplot2)
library(tidyverse)

matches_bracket <- matches_scores %>%
  filter(!is.na(home_score) & !is.na(away_score)) %>%
  mutate(round = case_when(
    tour == "huitiemes" ~ "8èmes de finale",
    tour == "quarts" ~ "Quarts de finale",
    tour == "demis" ~ "Demi-finales",
    tour == "finale" ~ "Finale"
  )) %>%
  select(round, homeTeam_name, awayTeam_name, winner) %>%
  pivot_longer(cols = c(homeTeam_name, awayTeam_name), names_to = "position", values_to = "team") %>%
  mutate(position = if_else(position == "homeTeam_name", "left", "right"))

team_heights <- matches_bracket %>%
  group_by(team) %>%
  summarize(y = mean(as.numeric(factor(round))), .groups = "drop") %>%
  arrange(desc(y))

ggplot(matches_bracket, aes(y = team, x = round, color = winner)) +
  geom_segment(aes(x = round, xend = lead(round), y = team, yend = team), size = 1) +
  geom_point(size = 3) +
  scale_color_manual(values = c("red", "blue", "grey", "green", "purple", "orange", "yellow", "pink", "brown", "black"),guide = FALSE) +
  theme_minimal() +
  labs(x = NULL, y = NULL, fill = NULL) +
  coord_flip() +
  expand_limits(y = c(levels(matches_bracket$team), NA)) +
  geom_text(aes(x = lead(round), y = team, label = team), hjust = 0, size = 3, nudge_x = 0.1, fontface = "bold")


```

# Web Scraping

Nous nous intéressons à la page wikipédia de l'édition 2020-2021 de la Ligue des champions : 
https://fr.wikipedia.org/wiki/Ligue_des_champions_de_l%27UEFA_2020-2021

```{r}

```












